# Generated by Django 4.2.12 on 2024-09-23 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Digital_doc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdemande',
            name='id_citoyen',
        ),
    ]
